-- review_bi — Supabase schema
--
-- Caches app metadata and reviews normally fetched live from iTunes on
-- every request, so most reads can be served from our own database
-- instead of depending on Apple's APIs (which have rate-limited us
-- before). A separate sync job (future task) populates and refreshes
-- these tables; this migration only creates the schema.
--
-- How to (re)apply: paste this whole file into the Supabase dashboard's
-- SQL Editor for the project and run it. It's idempotent (IF NOT EXISTS /
-- OR REPLACE throughout), so re-running it after partial application is
-- safe.
--
-- Approach chosen: a single hand-run SQL file versioned in the repo,
-- rather than a numbered migrations directory — this project has exactly
-- one schema (no prior migrations to chain from), so a single reproducible
-- script is simpler than migration tooling for now. If the schema starts
-- evolving with real data in the tables, switch to versioned migrations
-- (e.g. the Supabase CLI's supabase/migrations/) instead of editing this
-- file in place.

-- ---------------------------------------------------------------------
-- apps — one row per iTunes app we track, refreshed by the sync job.
-- ---------------------------------------------------------------------
create table if not exists apps (
  track_id             bigint primary key,       -- real iTunes trackId, never autogenerated
  track_name           text not null,
  artist_name          text,
  artwork_url_100      text,
  primary_genre_name   text,
  average_user_rating  numeric,
  user_rating_count    integer,
  country              text default 'cl',
  source               text,                      -- 'seed_carousel' | 'seed_category' | 'seed_guaranteed' | 'organic'
  last_synced_at       timestamptz,
  created_at           timestamptz default now(),
  -- ALV-85 fix: last_synced_at alone isn't proof reviews were actually
  -- saved — Santander Chile (track_id 604982236) had last_synced_at set
  -- from the initial seed run, but 0 rows in `reviews`, because that
  -- run's live RSS fetch for it silently returned an empty result (HTTP
  -- 200, no exception) despite Apple genuinely having ~50k+ reviews for
  -- it — indistinguishable, at the code level, from a real 0-review app,
  -- until a later request confirmed it isn't. reviews_confirmed_empty is
  -- only ever set true when a fetch AND the subsequent reviews save (if
  -- there were any rows to save) both completed successfully in the same
  -- run — see lib/reviews.ts and app/api/cron/sync-apps for every write
  -- site. It's the signal fetchReviews uses to skip a live re-fetch, not
  -- last_synced_at.
  reviews_confirmed_empty boolean not null default false
);

-- ---------------------------------------------------------------------
-- reviews — one row per iTunes customer review, keyed by iTunes' own
-- review id so re-syncing the same review upserts instead of duplicating.
-- ---------------------------------------------------------------------
create table if not exists reviews (
  id           text primary key,                 -- iTunes RSS entry.id.label, not autogenerated
  track_id     bigint not null references apps (track_id) on delete cascade,
  author       text,
  title        text,
  content      text,
  rating       integer,
  review_date  text,                              -- raw ISO string as iTunes sends it, unparsed
  app_version  text,
  country      text,
  fetched_at   timestamptz default now()
);

-- Speeds up "all reviews for this app" lookups, the main query shape.
create index if not exists reviews_track_id_idx on reviews (track_id);

-- ALV-85 fix, applied to the already-existing production table: the
-- column is defined inline above for a from-scratch CREATE TABLE, but
-- `create table if not exists` is a no-op against a table that already
-- exists — this ALTER is what actually reaches the live `apps` table.
-- Safe to re-run (IF NOT EXISTS).
alter table apps add column if not exists reviews_confirmed_empty boolean not null default false;

-- ---------------------------------------------------------------------
-- pending_apps — queue of organically-searched apps not yet cached, for
-- the sync job to pick up.
-- ---------------------------------------------------------------------
create table if not exists pending_apps (
  track_id      bigint primary key,
  requested_at  timestamptz default now(),
  attempts      integer default 0,
  last_error    text
);

-- ---------------------------------------------------------------------
-- Row Level Security — enabled with NO policies on all three tables.
-- All app traffic goes through our Next.js API routes using
-- SUPABASE_SECRET_KEY, which bypasses RLS entirely, so this isn't
-- required for the app to work. It's a defense-in-depth layer: with RLS
-- enabled and zero policies, the public/anon key (which we never use)
-- is denied all access instead of defaulting to open.
-- ---------------------------------------------------------------------
alter table apps enable row level security;
alter table reviews enable row level security;
alter table pending_apps enable row level security;
