-- review_bi — Supabase schema
--
-- Caches app metadata and reviews normally fetched live from iTunes on
-- every request, so most reads can be served from our own database
-- instead of depending on Apple's APIs (which have rate-limited us
-- before). A separate sync job (future task) populates and refreshes
-- these tables; this migration only creates the schema.
--
-- How to (re)apply: paste this whole file into the Supabase dashboard's
-- SQL Editor for the project and run it. It's idempotent (IF NOT EXISTS /
-- OR REPLACE throughout), so re-running it after partial application is
-- safe.
--
-- Approach chosen: a single hand-run SQL file versioned in the repo,
-- rather than a numbered migrations directory — this project has exactly
-- one schema (no prior migrations to chain from), so a single reproducible
-- script is simpler than migration tooling for now. If the schema starts
-- evolving with real data in the tables, switch to versioned migrations
-- (e.g. the Supabase CLI's supabase/migrations/) instead of editing this
-- file in place.

-- ---------------------------------------------------------------------
-- apps — one row per iTunes app we track, refreshed by the sync job.
-- ---------------------------------------------------------------------
create table if not exists apps (
  track_id             bigint primary key,       -- real iTunes trackId, never autogenerated
  track_name           text not null,
  artist_name          text,
  artwork_url_100      text,
  primary_genre_name   text,
  average_user_rating  numeric,
  user_rating_count    integer,
  country              text default 'cl',
  source               text,                      -- 'seed_carousel' | 'seed_category' | 'organic'
  last_synced_at       timestamptz,
  created_at           timestamptz default now()
);

-- ---------------------------------------------------------------------
-- reviews — one row per iTunes customer review, keyed by iTunes' own
-- review id so re-syncing the same review upserts instead of duplicating.
-- ---------------------------------------------------------------------
create table if not exists reviews (
  id           text primary key,                 -- iTunes RSS entry.id.label, not autogenerated
  track_id     bigint not null references apps (track_id) on delete cascade,
  author       text,
  title        text,
  content      text,
  rating       integer,
  review_date  text,                              -- raw ISO string as iTunes sends it, unparsed
  app_version  text,
  country      text,
  fetched_at   timestamptz default now()
);

-- Speeds up "all reviews for this app" lookups, the main query shape.
create index if not exists reviews_track_id_idx on reviews (track_id);

-- ---------------------------------------------------------------------
-- pending_apps — queue of organically-searched apps not yet cached, for
-- the sync job to pick up.
-- ---------------------------------------------------------------------
create table if not exists pending_apps (
  track_id      bigint primary key,
  requested_at  timestamptz default now(),
  attempts      integer default 0,
  last_error    text
);

-- ---------------------------------------------------------------------
-- Row Level Security — enabled with NO policies on all three tables.
-- All app traffic goes through our Next.js API routes using
-- SUPABASE_SECRET_KEY, which bypasses RLS entirely, so this isn't
-- required for the app to work. It's a defense-in-depth layer: with RLS
-- enabled and zero policies, the public/anon key (which we never use)
-- is denied all access instead of defaulting to open.
-- ---------------------------------------------------------------------
alter table apps enable row level security;
alter table reviews enable row level security;
alter table pending_apps enable row level security;
